apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /bitnami/kafka
    type: DirectoryOrCreate
  
